[profile.default]
solc = '0.8.23'
evm_version = 'paris'
via_ir = true
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 10_000_000
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 5000

[fmt]
ignore = ['src/external/**/*']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
